apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorillas-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gorillas-frontend
  template:
    metadata:
      labels:
        app: gorillas-frontend
    spec:
      containers:
      - name: gorillas-frontend
        image: gorillas-frontend:latest
        ports:
        - containerPort: 9563
---
apiVersion: v1
kind: Service
metadata:
  name: gorillas-frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9563
  selector:
    app: gorillas-frontend 